### ISSUE TITLE
XD84 is not supported by latest TKG.IO ?

### ISSUE THREAD

**Issue by Gash21** [kairyu/tkg#26]
Keyboard : XD84 using Kimera Core

Hi, i'm new on custom keyboard, i want to ask about https://tkg.io
I'm using guide provided by XD84 [(link)](https://drive.google.com/open?id=0B36cphsDCP8Zc3RvLWItQ2lVdVE) and also using layout provided on that docs, but when i burn .eep only function key is exported to my keyboard (fn0 - fn9) and the others (alpha key, f1-12, etc) is not assigned on keyboard, is there's something wrong?

Thanks and sorry for my bad english.

**Comment by anjari** [comment]
Try https://kai.tkg.io instead of https://tkg.io.

**Comment by Gash21** [comment]
@anjari 
thanks for your answer, i'm forgot to resolve this issue, Anyway i think the problem is on my windows 10, newbie mistakes i think, i was wrong when installing driver for my KB on my pc using zadig, on other pc, my keyboard is works well, right now i'm typing using my XD84.
