### ISSUE TITLE
What key is the magic salt key

### ISSUE THREAD

**Issue by vizee** [kairyu/tkg#30]
I have disabled GUI keys, but I can't enable them by magic boot:
* https://github.com/tmk/tmk_keyboard#magic-commands
* https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/bootmagic.h

Is magic salt key mapped to another key? or may I disable magic boot by TKG?

Help me please!

**Comment by jeffreylsoffer** [comment]
Hi. I am also struggling with this! It doesn't seem to be the spacebar, unless I'm doing something wrong. I can't reenable my GUI key.

**Comment by vizee** [comment]
> Hi. I am also struggling with this! It doesn't seem to be the spacebar, unless I'm doing something wrong. I can't reenable my GUI key.

I resolve it by re-flashing the ROM using tkg-toolkit

**Comment by jeffreylsoffer** [comment]
Yeah....just reflashed it and it's all working now. Bummer that I have no idea what caused it and annoying if it is cmd+space since that's definitely 2 keys i hit together a lot for spotlight!
