### ISSUE TITLE
Tilde/Backtick key isn't recognized

### ISSUE THREAD

**Issue by GLosch** [kairyu/tkg#7]
The tilde/backtick key (` and ~) isn't recognized as a valid key option:
![image](https://cloud.githubusercontent.com/assets/5502159/19253685/f8520726-8f1a-11e6-85ff-287aebe2beca.png)

**Comment by kairyu** [comment]
TKG recognized such keys by the combination of the legends. Please put ``` ` ``` into "Top Legend" and put ``` ~ ``` into "Bottom Legend" just like the other number keys.

![temp](https://cloud.githubusercontent.com/assets/3370483/19257158/53fb7a02-8fa8-11e6-91a9-1684f3fc1e15.png)

**Comment by kairyu** [comment]
If you still have any problem, please re-open this issue.

**Comment by AviateX14** [comment]
I hate to dredge up an old issue but I'm basically in the same boat, I'm trying to get the backtick as an fn option on the esc key, this isn't working (unknown label). Additionally, I can't get insert to work, I've 
added it to a key, flashed it, but it does nothing. Here's the TKG error:

![Error](http://i.imgur.com/PfMqrwX.jpg)

[Here's my layout](http://www.keyboard-layout-editor.com/##@_backcolor=%23c9c9c9&name=Red%20Scarf%2068II+%20rev%20C&author=Dotchoucou&notes=%220%22%2F:%5B%22ACTION%2F_LAYER%2F_MOMENTARY%22,1%5D,%221%22%2F:%5B%22ACTION%2F_FUNCTION%22,2,0%5D,%222%22%2F:%5B%22ACTION%2F_FUNCTION%22,4,0%5D,%223%22%2F:%5B%22ACTION%2F_FUNCTION%22,3,0%5D,%224%22%2F:%5B%22ACTION%2F_FUNCTION%22,7,0%5D,%225%22%2F:%5B%22ACTION%2F_FUNCTION%22,7,1%5D,%226%22%2F:%5B%22ACTION%2F_NO%22%5D,%227%22%2F:%5B%22ACTION%2F_NO%22%5D,%228%22%2F:%5B%22ACTION%2F_NO%22%5D,%229%22%2F:%5B%22ACTION%2F_NO%22%5D,%2210%22%2F:%5B%22ACTION%2F_NO%22%5D,%2211%22%2F:%5B%22ACTION%2F_NO%22%5D,%2212%22%2F:%5B%22ACTION%2F_NO%22%5D,%2213%22%2F:%5B%22ACTION%2F_BACKLIGHT%2F_TOGGLE%22%5D,%2214%22%2F:%5B%22ACTION%2F_BACKLIGHT%2F_DECREASE%22%5D,%2215%22%2F:%5B%22ACTION%2F_BACKLIGHT%2F_INCREASE%22%5D,%2216%22%2F:%5B%22ACTION%2F_BACKLIGHT%2F_STEP%22%5D,%2217%22%2F:%5B%22ACTION%2F_NO%22%5D,%2218%22%2F:%5B%22ACTION%2F_NO%22%5D,%2219%22%2F:%5B%22ACTION%2F_NO%22%5D,%2220%22%2F:%5B%22ACTION%2F_NO%22%5D,%2221%22%2F:%5B%22ACTION%2F_NO%22%5D,%2222%22%2F:%5B%22ACTION%2F_NO%22%5D,%2223%22%2F:%5B%22ACTION%2F_NO%22%5D,%2224%22%2F:%5B%22ACTION%2F_NO%22%5D,%2225%22%2F:%5B%22ACTION%2F_NO%22%5D,%2226%22%2F:%5B%22ACTION%2F_NO%22%5D,%2227%22%2F:%5B%22ACTION%2F_NO%22%5D,%2228%22%2F:%5B%22ACTION%2F_NO%22%5D,%2229%22%2F:%5B%22ACTION%2F_NO%22%5D,%2230%22%2F:%5B%22ACTION%2F_NO%22%5D,%2231%22%2F:%5B%22ACTION%2F_KEY%22,%22KC%2F_PAUSE%22%5D&switchMount=cherry&switchBrand=cherry&switchType=MX1A-C1xx&plate:true%3B&@_x:2.25&c=%23ff0000%3B&=esc%0A%0A%0A%0A%60&_c=%23cccccc%3B&=!%0A1%0A%0A%0Af1&=%22%0A2%0A%0A%0Af2&=%C2%A3%0A3%0A%0A%0Af3&=$%0A4%0A%0A%0Af4&=%25%0A5%0A%0A%0Af5&=%5E%0A6%0A%0A%0Af6&=%2F&%0A7%0A%0A%0Af7&=*%0A8%0A%0A%0Af8&=(%0A9%0A%0A%0Af9&=)%0A0%0A%0A%0Af10&=%2F_%0A-%0A%0A%0Af11&=+%0A%2F=%0A%0A%0Af12&_c=%23999999&w:2%3B&=Backspace%0A%0A%0A%0Adel&=home%0A%0A%0A%0Aprint%3B&@_x:2.25&w:1.5%3B&=tab&_c=%23cccccc%3B&=Q%0A%0A%0A%0Afn1&=W%0A%0A%0A%0Afn2&=E%0A%0A%0A%0Afn3&=R%0A%0A%0A%0Afn4&=T%0A%0A%0A%0Afn5&=Y%0A%0A%0A%0Afn6&=U%0A%0A%0A%0Afn7&=I%0A%0A%0A%0Afn8&=O%0A%0A%0A%0Afn9&=P%0A%0A%0A%0Afn10&=%7B%0A%5B%0A%0A%0Afn11&=%7D%0A%5D%0A%0A%0Afn12&_x:0.25&c=%23999999&sm=cherry&w:1.25&h:2&w2:1.5&h2:1&x2:-0.25%3B&=enter&=insert%0A%0A%0A%0Avolup%3B&@_x:2.25&w:1.75%3B&=caps&_c=%23cccccc%3B&=A%0A%0A%0A%0Afn13&=S%0A%0A%0A%0Afn14&=D%0A%0A%0A%0Afn15&=F%0A%0A%0A%0Afn16&=G%0A%0A%0A%0Afn17&=H%0A%0A%0A%0Afn18&=J%0A%0A%0A%0Afn19&=K%0A%0A%0A%0Afn20&=L%0A%0A%0A%0Afn21&=%2F:%0A%2F%3B%0A%0A%0Afn22&=%2F@%0A'%0A%0A%0Afn23&=~%0A%23%0A%0A%0Afn24&_x:1.25&c=%23999999%3B&=pgup%0A%0A%0A%0Avoldn%3B&@_x:2.25&w:1.25%3B&=shift&=iso%20%7C%0A%5C&_c=%23cccccc%3B&=Z%0A%0A%0A%0Afn25&=X%0A%0A%0A%0Afn26&=C%0A%0A%0A%0Afn27&=V%0A%0A%0A%0Afn28&=B%0A%0A%0A%0Afn29&=N%0A%0A%0A%0Afn30&=M&=%3C%0A,&=%3E%0A.&=%3F%0A%2F%2F&_c=%23999999&w:1.75%3B&=shift&=%E2%86%91%0A%0A%0A%0Apgup&=pgdn%3B&@_x:2.25&w:1.25%3B&=ctrl&_w:1.25%3B&=win&_w:1.25%3B&=alt&_c=%23cccccc&w:6.25%3B&=spacebar&_c=%23999999%3B&=altgr&=fn0&=ctrl%0A%0A%0A%0Amute&=%E2%86%90%0A%0A%0A%0Ahome&=%E2%86%93%0A%0A%0A%0Apgdn&=%E2%86%92%0A%0A%0A%0Aend)

Here's the JSON:

```
[{x:2.25,c:"#ff0000"},"esc\n\n\n\n`",{c:"#cccccc"},"!\n1\n\n\nf1","\"\n2\n\n\nf2","£\n3\n\n\nf3","$\n4\n\n\nf4","%\n5\n\n\nf5","^\n6\n\n\nf6","&\n7\n\n\nf7","*\n8\n\n\nf8","(\n9\n\n\nf9",")\n0\n\n\nf10","_\n-\n\n\nf11","+\n=\n\n\nf12",{c:"#999999",w:2},"Backspace\n\n\n\ndel","home\n\n\n\nprint"],
[{x:2.25,w:1.5},"tab",{c:"#cccccc"},"Q\n\n\n\nfn1","W\n\n\n\nfn2","E\n\n\n\nfn3","R\n\n\n\nfn4","T\n\n\n\nfn5","Y\n\n\n\nfn6","U\n\n\n\nfn7","I\n\n\n\nfn8","O\n\n\n\nfn9","P\n\n\n\nfn10","{\n[\n\n\nfn11","}\n]\n\n\nfn12",{x:0.25,c:"#999999",sm:"cherry",w:1.25,h:2,w2:1.5,h2:1,x2:-0.25},"enter","insert\n\n\n\nvolup"],
[{x:2.25,w:1.75},"caps",{c:"#cccccc"},"A\n\n\n\nfn13","S\n\n\n\nfn14","D\n\n\n\nfn15","F\n\n\n\nfn16","G\n\n\n\nfn17","H\n\n\n\nfn18","J\n\n\n\nfn19","K\n\n\n\nfn20","L\n\n\n\nfn21",":\n;\n\n\nfn22","@\n'\n\n\nfn23","~\n#\n\n\nfn24",{x:1.25,c:"#999999"},"pgup\n\n\n\nvoldn"],
[{x:2.25,w:1.25},"shift","iso |\n\\",{c:"#cccccc"},"Z\n\n\n\nfn25","X\n\n\n\nfn26","C\n\n\n\nfn27","V\n\n\n\nfn28","B\n\n\n\nfn29","N\n\n\n\nfn30","M","<\n,",">\n.","?\n/",{c:"#999999",w:1.75},"shift","↑\n\n\n\npgup","pgdn"],
[{x:2.25,w:1.25},"ctrl",{w:1.25},"win",{w:1.25},"alt",{c:"#cccccc",w:6.25},"spacebar",{c:"#999999"},"altgr","fn0","ctrl\n\n\n\nmute","←\n\n\n\nhome","↓\n\n\n\npgdn","→\n\n\n\nend"]

```
